let db = {};

db.nadsat = {
  men: "chellovecks",
  money: "cutter",
  corny: "Hound-and-Horny",
  angry: "razdraz",
  woman: "baboochka",
  bad: "baddiwad",
  band: "banda",
  prison: "barry",
  bed: "bedways",
  crazy: "bezoomny",
  library: "biblio",
  battle: "bitva",
  cry: "blub",
  godman: "bogman",
  thunder: "boomaboom",
  sick: "bolnoy",
  big: "bolshy",
  upset: "boohoohoo",
  boutique: "bootick",
  brother: "brat",
  bastard: "bratchny",
  razor: "britva,",
  belly: "brooko",
  police: "bruiseboys",
  riches: "bugatties",
  rich: "bugatty",
  vessels: "cables",
  cigarette: "crap cancer",
  office: "cantora",
  pocket: "carman",
  tea: "chai",
  chaplain: "charlie",
  cup: "chasha",
  guard: "chasso",
  woman: "cheena",
  wash: " cheest",
  cperson: "helloveck",
  nonsense: "chepooka",
  wonderful: "choodessny",
  mumble: "chumble",
  cinema: "cine",
  knock: "clop",
  beak: "cluve",
  bell: "collocoll",
  howl: "crark",
  steal: "crast",
  shout: "creech",
  elder: "decrep",
  oldman: "dedoochka",
  girl: "devotchka",
  dobby: "good",
  ghost: "dook",
  house: "domy"
};

module.exports = db;
